### ISSUE TITLE
usePageHeight() from react-ember-sdk is not working

### ISSUE THREAD

**Issue by rytis-convious** [sigmacomputing/embed-sdk#62]
Hi,

it seams that usePageHeight() has no effect and returned value is just `undefined`. 

My setup:

`App.tsx`

```tsx
import './App.css'
import { usePageHeight, useSigmaIframe } from '@sigmacomputing/react-embed-sdk'

const EMBED_URL = 'https://app.sigmacomputing.com/embed/my-public-workbook'

function App() {

  const { iframeRef } = useSigmaIframe()
  const height = usePageHeight(iframeRef)
  console.log('height', height) // <- outputs undefined

  return (
    <div className="container">
      <iframe ref={iframeRef} style={{height}} src={EMBED_URL} />
    </div>
  )
}

export default App
```

`App.css`

```css
:root {
  background-color: green;
}

.container {
  display: flex;
  flex-direction: column;
  background-color: blue;
  width: 100%;
  iframe {
    margin: 0 2rem; /* <- just to show that scrollbars are within iframe */
    flex-grow: 1;
  }
}
```

In the screenshot you may see the iframe with default height set by a browser to 150px. Green area is `body` element, blue is `div.container`.

<img width="1342" alt="image" src="https://github.com/user-attachments/assets/5bd2991f-a949-4ada-b619-0935f8241e12">
